[package]
name = "rust_sitter_example"
version = "0.1.0"
authors = ["Shadaj Laddad <shadaj@users.noreply.github.com>"]
edition = "2021"

[dependencies]
rust_sitter = { path = "../runtime" }
tree-sitter = "0.20.6"

[build-dependencies]
cc = "*"
tempdir = "0.3.7"
tree-sitter-cli = "0.20.6"
tree-sitter = "0.20.6"
rust_sitter_tool = { path = "../tool" }

[dev-dependencies]
insta = "1.7.1"
