[package]
name = "rust_sitter"
description = "A package for defining tree-sitter grammars alongside Rust logic"
readme = "../README.md"
version = "0.1.0"
authors = ["Shadaj Laddad <shadaj@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
keywords = ["parsing", "codegen"]
categories = ["development-tools"]

[lib]
path = "src/lib.rs"

[dependencies]
tree-sitter = "0.20.6"
rust_sitter_macro = { path = "../macro" }

[dev-dependencies]
insta = "1.7.1"
tempfile = "3.2.0"
