[package]
name = "rust_sitter_tool"
description = "The external tool for rust-sitter that extracts grammars from Rust definitions"
version = "0.1.0"
authors = ["Shadaj Laddad <shadaj@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
keywords = ["parsing", "codegen"]
categories = ["development-tools"]

[dependencies]
syn = { version = "1.0", features = [ "full", "extra-traits" ] }
syn-inline-mod = "0.5.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
insta = "1.7.1"
